# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180412_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
