# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180412_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=20)),
                ('acad_year', models.CharField(max_length=10)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('ccode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('rollno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='enrolled',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolled',
            unique_together=set([('rollno', 'acad_year', 'semester', 'ccode')]),
        ),
    ]
