# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
